### ISSUE TITLE
bug in model dependency 

### ISSUE THREAD

**Issue by dalinvip** [ttpro1995/TreeLSTMSentiment#2]
- run python sentiment.py --name de --model_name dependency --epochs 10 has a bug.
`
tree.state = self.node_forward(embs[tree.idx-1], child_c, child_h)
IndexError: index 48 is out of bounds for dimension 0 with size 27
`
please, how to solve it?

**Comment by byecc** [comment]
delete all preloaded data ( delete all. pth file in working directory). ttpro told me.

**Comment by dalinvip** [comment]
ok , solve it by `rm ./data/*.pth`
thanks.
