### ISSUE TITLE
Index out of range error for very common case

### ISSUE THREAD

**Issue by tosiecki** [ttpro1995/TreeLSTMSentiment#6]
Hey ttpro1995,

  Thanks for producing this code.  I run the dependency version fine, but when I run:

python sentiment.py --name constituency_log.txt --model_name constituency --epochs 10

I get the following stack trace:

```Traceback (most recent call last):
  File "sentiment.py", line 228, in <module>
    main()
  File "sentiment.py", line 184, in main
    train_loss = trainer.train(train_dataset)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/trainer.py", line 37, in train
    output, err = self.model.forward(tree, emb, training = True)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 366, in forward
    tree_state, loss = self.tree_module(tree, inputs, training)
  File "/Users/tosiecki/Tom/env2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 156, in forward
    _, child_loss = self.forward(tree.children[idx], embs, training)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 156, in forward
    _, child_loss = self.forward(tree.children[idx], embs, training)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 156, in forward
    _, child_loss = self.forward(tree.children[idx], embs, training)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 158, in forward
    lc, lh, rc, rh = self.get_child_state(tree)
  File "/Users/tosiecki/Tom/TreeLSTMSentiment/model.py", line 174, in get_child_state
    rc, rh = tree.children[1].state
IndexError: list index out of range
```
but it is very very common to have a tree with 1 child.  How was this handled when you were testing?  I tried to add a elif tree.num_children == 1 case, but I'm not super familiar with what should go here and it is a hack.  Do you have any suggestions as to how to fix this?

Tom.

**Comment by tosiecki** [comment]
I made the following hack and it seems to be training now, but I'm not sure how correct it is:

```
def get_child_state(self, tree):
        lc, lh = tree.children[0].state
        if tree.num_children < 2:
            rc = torch.zeros([1, 150])
            rh = torch.zeros([1, 150])
        else:
            rc, rh = tree.children[1].state
        return lc, lh, rc, rh
```

**Comment by ttpro1995** [comment]
Please look at https://github.com/ttpro1995/TreeLSTMSentiment/issues/2 if it is your case.

Because preprocess data, embedding model (caching to save preprocess time), you may end up using preprocess data of dependency tree for constituency tree. 

delete all. pth file in working directory

**Comment by ttpro1995** [comment]
hi @tosiecki , how it going ?

**Comment by tosiecki** [comment]
Hey @ttpro1995, I was able to do what you suggested and it worked, thank you so much.  I had a misunderstanding as to how the two modes (dep vers constit) operated.
