### ISSUE TITLE
javac can'not find lib/*.java

### ISSUE THREAD

**Issue by ghost** [ttpro1995/TreeLSTMSentiment#7]
Hello 
When I run "fetch_and_preprocess.sh", there is an error:
javac: can not find file: lib/*.java

**Comment by ttpro1995** [comment]
Hi @ssnvxia 
 "fetch_and_preprocess.sh" will look at .java in https://github.com/ttpro1995/TreeLSTMSentiment/tree/master/lib 

You may need to open your terminal at project root, so `lib/*.java` point to right folder

**Comment by ttpro1995** [comment]
the script will also run `download.py`  to download 3rd party jar (lib/stanford-parser/stanford-parser.jar:lib/stanford-parser/stanford-parser-3.5.1-models.jar). Make sure you download these file succesfully. 

Something might happen when you run behind university/company firewall, so if you can't download something, try on your home network.

**Comment by ghost** [comment]
Thank you ! I got it
